server:
  port: 8081
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

spring:
  application:
    name: ms-inventory-products

  datasource:
      url: jdbc:mysql://localhost:3306/itempruebauno
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect


## Configuracion del cliente de Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-inventory-products
